-- ============================================================
-- CCAvenue credential bag + static UPI QR collections
-- Hand-authored migration (not generated by `prisma migrate dev`)
-- ------------------------------------------------------------
-- Column names are Prisma's defaults (camelCase, quoted) to stay
-- consistent with the rest of this service's schema, which does not
-- use per-column @map(). Table names are snake_case via @@map.
--
-- Razorpay's existing testKeyId / *SecretEnc columns are NOT migrated:
-- the credential bag is purely additive, so no live secret moves.
-- ============================================================

-- AlterEnum
-- NOTE: `ALTER TYPE ... ADD VALUE` cannot run inside a transaction block on
-- PostgreSQL versions older than 12. It is isolated and placed first, and on
-- PG < 12 this statement must be executed separately (outside the migration
-- transaction). This is the same caveat the previous payment migration
-- documents for `transaction_type`.
ALTER TYPE "payment_order_kind" ADD VALUE 'QR_STATIC';

-- AlterTable
-- Additive, nullable credential bag. Shape:
--   { "<fieldName>": { "v": "<plaintext>" } | { "enc": "<AES-256-GCM envelope>" } }
-- NEVER expose these columns through SAFE_SELECT - they carry envelopes.
ALTER TABLE "payment_provider_configs" ADD COLUMN "testCredentials" JSONB;
ALTER TABLE "payment_provider_configs" ADD COLUMN "liveCredentials" JSONB;

-- CreateEnum
CREATE TYPE "qr_collection_source" AS ENUM ('WEBHOOK', 'IMPORT', 'MANUAL', 'POLL');

-- CreateEnum
CREATE TYPE "qr_collection_status" AS ENUM ('UNATTRIBUTED', 'ASSIGN_PENDING', 'ATTRIBUTED', 'CREDIT_PENDING', 'CREDITED', 'REJECTED', 'IGNORED');

-- Strong (bank UTR) vs weak (content hash) idempotency key. Recorded so an
-- operator can tell them apart without re-deriving the hash.
CREATE TYPE "qr_dedupe_strategy" AS ENUM ('UTR', 'CONTENT');

-- Why a collection sits in the unattributed queue. Typed rather than buried in
-- metadata JSON so the ops queue is filterable without a JSON predicate.
CREATE TYPE "qr_unattributed_reason" AS ENUM ('NO_QR_MATCH', 'INACTIVE_QR', 'NO_UTR');

-- CreateTable
-- The attribution key. Creating a row, or repointing one to a different
-- "walletUserId", is a MONEY-ROUTING change. "walletUserId" is deliberately
-- NOT a FK: Outlet lives in user-service, a different database.
CREATE TABLE "outlet_payment_qrs" (
    "id" UUID NOT NULL,
    "provider" VARCHAR(50) NOT NULL DEFAULT 'ccavenue_upi_qr',
    "walletUserId" VARCHAR(255) NOT NULL,
    "clientCode" VARCHAR(50) NOT NULL DEFAULT 'DEFAULT',
    "subjectUserId" UUID,
    "outletId" UUID,
    "outletName" VARCHAR(200),
    "qrIdentifier" VARCHAR(190),
    "vpa" VARCHAR(190),
    "qrPayload" TEXT,
    "qrImageUrl" TEXT,
    "mode" "payment_provider_mode" NOT NULL DEFAULT 'TEST',
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "label" VARCHAR(120),
    "maxPerCreditAmount" DECIMAL(15,2),
    "maxPerDayAmount" DECIMAL(15,2),
    "maxPerDayCount" INTEGER,
    "provisionedAt" TIMESTAMPTZ,
    "provisionedBy" UUID,
    "deactivatedAt" TIMESTAMPTZ,
    "deactivatedBy" UUID,
    "providerData" JSONB,
    "metadata" JSONB,
    "createdBy" UUID,
    "updatedBy" UUID,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "outlet_payment_qrs_pkey" PRIMARY KEY ("id")
);

-- CreateTable
-- The raw inbound row. WRITTEN UNCONDITIONALLY whether or not it matches an
-- outlet_payment_qrs row (mirroring cod_collections). "outletPaymentQrId" IS
-- NULL is what defines the unattributed queue.
CREATE TABLE "qr_collections" (
    "id" UUID NOT NULL,
    "provider" VARCHAR(50) NOT NULL DEFAULT 'ccavenue_upi_qr',
    "source" "qr_collection_source" NOT NULL DEFAULT 'WEBHOOK',
    "status" "qr_collection_status" NOT NULL DEFAULT 'UNATTRIBUTED',
    "utr" VARCHAR(64),
    "dedupeKey" VARCHAR(80) NOT NULL,
    "dedupeStrategy" "qr_dedupe_strategy" NOT NULL DEFAULT 'CONTENT',
    "unattributedReason" "qr_unattributed_reason",
    "deliveryCount" INTEGER NOT NULL DEFAULT 1,
    "providerTxnId" VARCHAR(190),
    "qrIdentifier" VARCHAR(190),
    "payerVpa" VARCHAR(190),
    "payerName" VARCHAR(255),
    "amount" DECIMAL(15,2) NOT NULL,
    "amountPaise" INTEGER NOT NULL,
    "currency" VARCHAR(3) NOT NULL DEFAULT 'INR',
    "txnAt" TIMESTAMPTZ,
    "receivedAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "outletPaymentQrId" UUID,
    "walletUserId" VARCHAR(255),
    "clientCode" VARCHAR(50),
    "subjectUserId" UUID,
    "mode" "payment_provider_mode",
    "paymentOrderId" UUID,
    "manualTopupRequestId" UUID,
    "externalReferenceId" VARCHAR(255),
    "attributedBy" UUID,
    "attributedAt" TIMESTAMPTZ,
    "rejectedBy" UUID,
    "rejectedAt" TIMESTAMPTZ,
    "remarks" TEXT,
    "lastError" TEXT,
    "needsManualAction" BOOLEAN NOT NULL DEFAULT false,
    "rawPayload" JSONB,
    "metadata" JSONB,
    "createdBy" UUID,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "qr_collections_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "outlet_payment_qrs_walletUserId_clientCode_idx" ON "outlet_payment_qrs"("walletUserId", "clientCode");

-- CreateIndex
CREATE INDEX "outlet_payment_qrs_outletId_idx" ON "outlet_payment_qrs"("outletId");

-- CreateIndex
CREATE INDEX "outlet_payment_qrs_subjectUserId_idx" ON "outlet_payment_qrs"("subjectUserId");

-- CreateIndex
CREATE INDEX "outlet_payment_qrs_isActive_idx" ON "outlet_payment_qrs"("isActive");

-- CreateIndex
CREATE UNIQUE INDEX "qr_collections_dedupeKey_key" ON "qr_collections"("dedupeKey");

-- CreateIndex
CREATE INDEX "qr_collections_status_idx" ON "qr_collections"("status");

-- CreateIndex
CREATE INDEX "qr_collections_outletPaymentQrId_idx" ON "qr_collections"("outletPaymentQrId");

-- CreateIndex
CREATE INDEX "qr_collections_walletUserId_clientCode_idx" ON "qr_collections"("walletUserId", "clientCode");

-- CreateIndex
CREATE INDEX "qr_collections_utr_idx" ON "qr_collections"("utr");

-- CreateIndex
CREATE INDEX "qr_collections_qrIdentifier_idx" ON "qr_collections"("qrIdentifier");

-- CreateIndex
CREATE INDEX "qr_collections_receivedAt_idx" ON "qr_collections"("receivedAt");

-- CreateIndex
CREATE INDEX "qr_collections_paymentOrderId_idx" ON "qr_collections"("paymentOrderId");

-- CreateIndex
CREATE INDEX "qr_collections_status_receivedAt_idx" ON "qr_collections"("status", "receivedAt");
CREATE INDEX "qr_collections_unattributedReason_idx" ON "qr_collections"("unattributedReason");

-- AddForeignKey
ALTER TABLE "qr_collections" ADD CONSTRAINT "qr_collections_outletPaymentQrId_fkey" FOREIGN KEY ("outletPaymentQrId") REFERENCES "outlet_payment_qrs"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
-- Declared in raw DDL only (no Prisma relation), so PaymentOrder keeps no
-- back-reference field. ON DELETE SET NULL: losing the order must never
-- delete the evidence of money that arrived.
ALTER TABLE "qr_collections" ADD CONSTRAINT "qr_collections_paymentOrderId_fkey" FOREIGN KEY ("paymentOrderId") REFERENCES "payment_orders"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- ------------------------------------------------------------
-- Partial unique indexes (Prisma cannot express these).
-- The `WHERE "isActive"` clauses are LOAD-BEARING: a QR must be retirable and
-- re-issuable, while two *live* QRs claiming one identifier must be impossible.
-- ------------------------------------------------------------

-- CreateIndex
CREATE UNIQUE INDEX outlet_payment_qrs_provider_qrid_uniq
  ON outlet_payment_qrs (provider, "qrIdentifier") WHERE "qrIdentifier" IS NOT NULL AND "isActive";

-- CreateIndex
CREATE UNIQUE INDEX outlet_payment_qrs_provider_vpa_uniq
  ON outlet_payment_qrs (provider, vpa) WHERE vpa IS NOT NULL AND "isActive";

-- CreateIndex
CREATE UNIQUE INDEX outlet_payment_qrs_active_wallet_uniq
  ON outlet_payment_qrs (provider, "walletUserId", "clientCode") WHERE "isActive";

-- CreateIndex
CREATE UNIQUE INDEX qr_collections_provider_utr_uniq
  ON qr_collections (provider, utr) WHERE utr IS NOT NULL;

-- CreateIndex
CREATE UNIQUE INDEX qr_collections_payment_order_uniq
  ON qr_collections ("paymentOrderId") WHERE "paymentOrderId" IS NOT NULL;

-- CreateIndex
CREATE UNIQUE INDEX qr_collections_manual_request_uniq
  ON qr_collections ("manualTopupRequestId") WHERE "manualTopupRequestId" IS NOT NULL;

-- CreateIndex
-- Missing today; needed for UTR-keyed lookup of an existing payment order.
CREATE INDEX payment_orders_provider_payment_id_idx ON payment_orders ("providerPaymentId");
