"use client";

import { extractApiError } from "@/lib/utils";
import { useCallback, useEffect, useRef, useState } from "react";
import { skipToken } from "@reduxjs/toolkit/query/react";
import {
  useGetPaymentOrderStatusQuery,
  useInitiatePaymentMutation,
  useLazyGetPaymentOrderStatusQuery,
  useVerifyPaymentMutation,
} from "@/store/api/endpoints/paymentApi";
import type {
  InitiatePaymentCheckout,
  InitiatePaymentResponse,
  PaymentOrderStatusResponse,
} from "@/store/api/endpoints/paymentApi";
// `InitiatePaymentCheckout` is a type-only import from paymentApi.ts (owned
// by another agent this wave) rather than a local redefinition here - a
// type-only import is read-only and keeps this hook in sync with the real
// `/self/initiate` response shape instead of drifting from a local copy.
import type {
  RazorpayFailurePayload,
  RazorpaySuccessPayload,
} from "@/lib/razorpay";
import { postRedirect } from "@/lib/redirectPost";
import { usePaymentProvider } from "./usePaymentProvider";

export type TopupPhase =
  | "idle"
  | "creating"
  | "loading-sdk"
  | "checkout"
  | "redirecting"
  | "cancelled"
  | "failed"
  | "verifying"
  | "polling"
  | "credited"
  | "reconciling";

export interface UseWalletTopupArgs {
  /** Omit for own wallet. */
  targetUserId?: string;
  onCredited?: (amount: number, balanceAfter?: number) => void;
}

export interface UseWalletTopup {
  phase: TopupPhase;
  errorMessage: string | null;
  amountPaid: number | null;
  balanceAfter: number | null;
  orderId: string | null;
  isTest: boolean;
  elapsedSeconds: number;
  start(amount: number): Promise<void>;
  retry(): void;
  reset(): void;
  checkStatusNow(): void;
}

const RESUME_STORAGE_KEY = "pendingWalletTopup";
const RESUME_MAX_AGE_MS = 30 * 60 * 1000;
const POLL_BUDGET_SECONDS = 60;
const POLL_INTERVAL_FAST_MS = 2000;
const POLL_INTERVAL_SLOW_MS = 5000;
const POLL_FAST_WINDOW_SECONDS = 20;

interface ResumeRecord {
  orderId: string;
  amount: number;
  targetUserId?: string;
  ts: number;
}

function generateIdempotencyKey(): string {
  if (
    typeof crypto !== "undefined" &&
    typeof crypto.randomUUID === "function"
  ) {
    return crypto.randomUUID();
  }
  return `topup-${Date.now()}-${Math.random().toString(36).slice(2)}`;
}

/** All localStorage access is wrapped - private/incognito browsing throws on read/write. */
function readResumeRecord(): ResumeRecord | null {
  try {
    const raw = localStorage.getItem(RESUME_STORAGE_KEY);
    if (!raw) return null;
    return JSON.parse(raw) as ResumeRecord;
  } catch {
    return null;
  }
}

function writeResumeRecord(record: ResumeRecord): void {
  try {
    localStorage.setItem(RESUME_STORAGE_KEY, JSON.stringify(record));
  } catch {
    // ignore - private mode / storage quota
  }
}

function clearResumeRecord(): void {
  try {
    localStorage.removeItem(RESUME_STORAGE_KEY);
  } catch {
    // ignore - private mode / storage quota
  }
}

/** True for an RTK Query `FetchBaseQueryError`-shaped 401. */
function isUnauthorizedError(error: unknown): boolean {
  if (!error || typeof error !== "object") return false;
  return (error as { status?: unknown }).status === 401;
}

/**
 * Full wallet top-up checkout state machine, covering both:
 *  - seamless providers (Razorpay) that complete via a JS checkout modal, and
 *  - non-seamless providers (CCAvenue) that complete via a top-level
 *    form-POST redirect away from the SPA entirely, with the browser
 *    returning via a server-side 302 to /wallet/topup/callback.
 *
 * Kept out of the recharge modal component so the flow is testable and
 * reusable across every "Add Money" surface (own wallet, admin-on-behalf-of
 * a target user, etc).
 */
export function useWalletTopup(args: UseWalletTopupArgs = {}): UseWalletTopup {
  const { targetUserId, onCredited } = args;
  const { validateAmount } = usePaymentProvider();

  const [phase, setPhase] = useState<TopupPhase>("idle");
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const [amountPaid, setAmountPaid] = useState<number | null>(null);
  const [balanceAfter, setBalanceAfter] = useState<number | null>(null);
  const [orderId, setOrderId] = useState<string | null>(null);
  const [isTest, setIsTest] = useState(false);
  const [elapsedSeconds, setElapsedSeconds] = useState(0);

  /**
   * Mirrors `phase`. Razorpay's `ondismiss` / `payment.failed` callbacks
   * fire outside React's render cycle and would otherwise close over a
   * stale `phase` from whichever render registered them.
   */
  const phaseRef = useRef<TopupPhase>("idle");
  const setPhaseBoth = useCallback((next: TopupPhase) => {
    phaseRef.current = next;
    setPhase(next);
  }, []);

  /**
   * Regenerated by `reset()` / `retry()` and sent as `/initiate`'s
   * idempotencyKey. Combined with `inFlightRef` (below) and the modal's own
   * disabled-button guard, this is one of three layers preventing a double
   * charge.
   */
  const idempotencyKeyRef = useRef<string>(generateIdempotencyKey());
  const inFlightRef = useRef(false);
  const checkoutHandleRef = useRef<{ close: () => void } | null>(null);
  const lastAmountRef = useRef<number | null>(null);
  const onCreditedRef = useRef(onCredited);
  useEffect(() => {
    onCreditedRef.current = onCredited;
  }, [onCredited]);

  const [initiatePayment] = useInitiatePaymentMutation();
  const [verifyPayment] = useVerifyPaymentMutation();
  const [triggerCheckStatus] = useLazyGetPaymentOrderStatusQuery();

  const { data: pollData, error: pollError } = useGetPaymentOrderStatusQuery(
    orderId ?? skipToken,
    {
      skip: phase !== "polling",
      pollingInterval:
        elapsedSeconds < POLL_FAST_WINDOW_SECONDS
          ? POLL_INTERVAL_FAST_MS
          : POLL_INTERVAL_SLOW_MS,
      refetchOnMountOrArgChange: true,
    },
  );

  /** Maps a status snapshot (from polling or a manual check) onto phase/state. */
  const applyStatusResult = useCallback(
    (result: PaymentOrderStatusResponse) => {
      setIsTest(result.isTest);
      if (result.amount != null) setAmountPaid(result.amount);

      switch (result.status) {
        case "CREDITED":
          setPhaseBoth("credited");
          clearResumeRecord();
          onCreditedRef.current?.(result.amount);
          inFlightRef.current = false;
          break;
        case "FAILED":
        case "CANCELLED":
          setPhaseBoth("failed");
          setErrorMessage(result.reconcileError ?? "Payment failed.");
          clearResumeRecord();
          inFlightRef.current = false;
          break;
        case "RECONCILE_PENDING":
          setPhaseBoth("reconciling");
          break;
        case "CREATED":
        case "PENDING":
        case "PAID":
        default:
          // Keep polling - not yet a terminal state.
          break;
      }
    },
    [setPhaseBoth],
  );

  // Resume-in-progress top-up on mount (survives a page reload / tab close
  // mid-checkout, and - critically for the REDIRECT_POST flow - a full
  // browser navigation away to a non-seamless gateway and back via the
  // server's 302 to /wallet/topup/callback). Only hydrates when the record
  // is fresh and targets the same wallet this hook instance is scoped to.
  useEffect(() => {
    const record = readResumeRecord();
    if (!record) return;
    if (Date.now() - record.ts > RESUME_MAX_AGE_MS) {
      clearResumeRecord();
      return;
    }
    // A record written just before a REDIRECT_POST navigation may carry no
    // targetUserId (own-wallet top-ups never set one), which matches the
    // default `undefined` here - so this still resumes correctly for the
    // common case of a CCAvenue round trip.
    if (record.targetUserId !== targetUserId) return;

    setOrderId(record.orderId);
    setAmountPaid(record.amount);
    setPhaseBoth("polling");
    // Mount-only: intentionally does not re-run when targetUserId changes.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // Close any open checkout modal on unmount.
  useEffect(() => {
    return () => {
      checkoutHandleRef.current?.close();
    };
  }, []);

  // Elapsed-time ticker + 60s polling budget, active only while polling.
  useEffect(() => {
    if (phase !== "polling") {
      setElapsedSeconds(0);
      return;
    }
    const startedAt = Date.now();
    const interval = setInterval(() => {
      const secs = Math.floor((Date.now() - startedAt) / 1000);
      setElapsedSeconds(secs);
      if (secs >= POLL_BUDGET_SECONDS) {
        setPhaseBoth("reconciling");
      }
    }, 1000);
    return () => clearInterval(interval);
  }, [phase, setPhaseBoth]);

  // Apply each polled snapshot.
  useEffect(() => {
    if (phase !== "polling" || !pollData) return;
    applyStatusResult(pollData);
  }, [phase, pollData, applyStatusResult]);

  // A 401 while polling means the session token did not survive the round
  // trip to the gateway and back (e.g. it lives only in memory/Redux, not
  // persisted storage) - most likely after a REDIRECT_POST return. We
  // cannot keep polling an authenticated endpoint with no valid token, but
  // that says nothing about whether the payment itself succeeded, so this
  // degrades to the "reconciling" copy and NEVER "failed". Any other
  // polling error is a transient network hiccup that RTK Query's own
  // pollingInterval will simply retry.
  useEffect(() => {
    if (phase !== "polling" || !pollError) return;
    if (isUnauthorizedError(pollError)) {
      setPhaseBoth("reconciling");
    }
  }, [phase, pollError, setPhaseBoth]);

  const checkStatusNow = useCallback(() => {
    if (!orderId) return;
    triggerCheckStatus(orderId)
      .unwrap()
      .then((result) => applyStatusResult(result))
      .catch(() => {
        // Manual refresh failure is a network hiccup - polling/webhook
        // remain the source of truth, so just ignore it.
      });
  }, [orderId, triggerCheckStatus, applyStatusResult]);

  const start = useCallback(
    async (amount: number) => {
      if (inFlightRef.current) return;

      const validationError = validateAmount(amount);
      if (validationError) {
        setErrorMessage(validationError);
        return;
      }

      inFlightRef.current = true;
      lastAmountRef.current = amount;
      setErrorMessage(null);
      setAmountPaid(null);
      setBalanceAfter(null);
      setPhaseBoth("creating");

      let initiateResult: InitiatePaymentResponse;
      try {
        initiateResult = await initiatePayment({
          amount,
          currency: "INR",
          idempotencyKey: idempotencyKeyRef.current,
        }).unwrap();
      } catch (err: any) {
        setPhaseBoth("failed");
        setErrorMessage(
          extractApiError(
            err,
            "Could not start the payment. Please try again.",
          ),
        );
        inFlightRef.current = false;
        return;
      }

      setOrderId(initiateResult.orderId);
      setIsTest(initiateResult.mode === "TEST");

      const checkout: InitiatePaymentCheckout = initiateResult.checkout;

      // --- Non-seamless (CCAvenue-style) redirect flow ---------------
      if (checkout.type === "REDIRECT_POST") {
        if (!checkout.url || !checkout.fields) {
          // REDIRECT_FIELDS_UNAVAILABLE: a replayed order's form-POST
          // fields could not be re-derived server-side. There is no modal
          // to fall back to for this provider, so this is a hard failure -
          // never silently swap in a MODAL checkout the provider doesn't
          // support.
          setPhaseBoth("failed");
          setErrorMessage(
            checkout.error ?? "Could not start the payment. Please try again.",
          );
          inFlightRef.current = false;
          return;
        }

        // BEFORE ANYTHING ELSE: the browser is about to navigate away to
        // the gateway and unload this SPA entirely. This localStorage
        // record is the only thread back to this flow when the gateway's
        // server-side 302 lands on /wallet/topup/callback and the app
        // remounts from scratch - it stops being a "nice to have resume"
        // and becomes the sole continuation mechanism.
        writeResumeRecord({
          orderId: initiateResult.orderId,
          amount: initiateResult.amount,
          targetUserId,
          ts: Date.now(),
        });

        setPhaseBoth("redirecting");
        postRedirect(checkout.url, checkout.fields);
        // Do NOT clear inFlightRef here - the page is leaving, and there is
        // no "after" for this call stack to run in.
        return;
      }

      // --- Seamless (Razorpay-style) modal flow -----------------------
      // Dynamically imported so a CCAvenue-only deployment (no MODAL
      // checkout ever returned) never pulls in the Razorpay loader/wrapper
      // module or fetches Razorpay's CDN script.
      const { loadRazorpayScript, openRazorpayCheckout } =
        await import("@/lib/razorpay");

      setPhaseBoth("loading-sdk");
      const sdkLoaded = await loadRazorpayScript();
      if (!sdkLoaded) {
        setPhaseBoth("failed");
        setErrorMessage(
          "Could not reach the payment gateway. Check your connection or disable ad-blockers and try again.",
        );
        inFlightRef.current = false;
        return;
      }

      setPhaseBoth("checkout");
      writeResumeRecord({
        orderId: initiateResult.orderId,
        amount: initiateResult.amount,
        targetUserId,
        ts: Date.now(),
      });

      const handleSuccess = (payload: RazorpaySuccessPayload) => {
        setPhaseBoth("verifying");
        verifyPayment({
          orderId: initiateResult.orderId,
          razorpay_order_id: payload.razorpay_order_id,
          razorpay_payment_id: payload.razorpay_payment_id,
          razorpay_signature: payload.razorpay_signature,
        })
          .unwrap()
          .then((verifyResult) => {
            if (verifyResult.status === "CREDITED") {
              // The webhook beat us to it.
              setAmountPaid(initiateResult.amount);
              setBalanceAfter(verifyResult.balanceAfter ?? null);
              setPhaseBoth("credited");
              clearResumeRecord();
              onCreditedRef.current?.(
                initiateResult.amount,
                verifyResult.balanceAfter,
              );
              inFlightRef.current = false;
              return;
            }
            if (verifyResult.verified === false) {
              setPhaseBoth("failed");
              setErrorMessage(
                "Payment could not be verified. Please contact support if the amount was debited.",
              );
              clearResumeRecord();
              inFlightRef.current = false;
              return;
            }
            // verified === true but not yet CREDITED - fall back to polling
            // so the webhook-driven backend can finish crediting the wallet.
            setAmountPaid(initiateResult.amount);
            setBalanceAfter(verifyResult.balanceAfter ?? null);
            setPhaseBoth("polling");
            inFlightRef.current = false;
          })
          .catch(() => {
            // IMPORTANT: a network/throw error from verify must NEVER be
            // mapped to "failed". Razorpay has already charged the customer
            // by this point in the flow - /verify is only an accelerator,
            // and the webhook-driven backend reconciliation is the real
            // authority on whether the wallet gets credited. Treating a
            // verify network error as a payment failure would tell a
            // successfully-charged customer their payment failed, so we
            // fall back to polling instead.
            setPhaseBoth("polling");
            inFlightRef.current = false;
          });
      };

      const handleFailure = (payload: RazorpayFailurePayload) => {
        setPhaseBoth("failed");
        setErrorMessage(payload.error?.description ?? "Payment failed.");
        clearResumeRecord();
        inFlightRef.current = false;
      };

      checkoutHandleRef.current = openRazorpayCheckout(
        {
          key: initiateResult.keyId,
          amount: initiateResult.amountPaise,
          currency: initiateResult.currency,
          name: "Logistics Aggregator",
          description: "Wallet top-up",
          order_id: initiateResult.providerOrderId,
          prefill: initiateResult.prefill,
          notes: targetUserId ? { targetUserId } : undefined,
          modal: {
            ondismiss: () => {
              // Also fires right after a successful `handler` call, so only
              // treat it as a cancellation while we're still in "checkout".
              if (phaseRef.current === "checkout") {
                setPhaseBoth("cancelled");
                clearResumeRecord();
                inFlightRef.current = false;
              }
            },
          },
          handler: handleSuccess,
        },
        handleFailure,
      );
    },
    [
      initiatePayment,
      verifyPayment,
      validateAmount,
      targetUserId,
      setPhaseBoth,
    ],
  );

  const reset = useCallback(() => {
    checkoutHandleRef.current?.close();
    checkoutHandleRef.current = null;
    inFlightRef.current = false;
    idempotencyKeyRef.current = generateIdempotencyKey();
    lastAmountRef.current = null;
    clearResumeRecord();
    setErrorMessage(null);
    setAmountPaid(null);
    setBalanceAfter(null);
    setOrderId(null);
    setIsTest(false);
    setElapsedSeconds(0);
    setPhaseBoth("idle");
  }, [setPhaseBoth]);

  const retry = useCallback(() => {
    idempotencyKeyRef.current = generateIdempotencyKey();
    if (lastAmountRef.current != null) {
      void start(lastAmountRef.current);
    }
  }, [start]);

  return {
    phase,
    errorMessage,
    amountPaid,
    balanceAfter,
    orderId,
    isTest,
    elapsedSeconds,
    start,
    retry,
    reset,
    checkStatusNow,
  };
}

/**
 * @deprecated Use `useWalletTopup`. Kept as an alias for one release so any
 * import of the old Razorpay-specific name keeps working; only
 * `recharge-modal.tsx` used it, and that has been updated to the new name
 * directly.
 */
export const useRazorpayTopup = useWalletTopup;
