-- ============================================================
-- Payment gateway (Razorpay) top-up + provider settings
-- Hand-authored migration (not generated by `prisma migrate dev`)
-- ------------------------------------------------------------
-- Column names are Prisma's defaults (camelCase, quoted) to stay
-- consistent with the rest of this service's schema, which does not
-- use per-column @map(). Table names are snake_case via @@map.
-- ============================================================

-- AlterEnum
-- NOTE: `ALTER TYPE ... ADD VALUE` cannot run inside a transaction block on
-- PostgreSQL versions older than 12. It is placed first, and on PG < 12 this
-- statement must be executed separately (outside the migration transaction).
ALTER TYPE "transaction_type" ADD VALUE 'TOP_UP';

-- CreateEnum
CREATE TYPE "payment_provider_mode" AS ENUM ('TEST', 'LIVE');

-- CreateEnum
CREATE TYPE "payment_order_kind" AS ENUM ('SELF_SERVE', 'ADMIN_LINK');

-- CreateEnum
CREATE TYPE "payment_order_status" AS ENUM ('CREATED', 'PENDING', 'PAID', 'CREDITED', 'RECONCILE_PENDING', 'FAILED', 'EXPIRED', 'CANCELLED', 'REFUNDED');

-- CreateEnum
CREATE TYPE "manual_topup_status" AS ENUM ('PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'CREDITED', 'FAILED');

-- CreateTable
CREATE TABLE "payment_provider_configs" (
    "id" UUID NOT NULL,
    "clientId" UUID,
    "provider" VARCHAR(50) NOT NULL,
    "isEnabled" BOOLEAN NOT NULL DEFAULT false,
    "mode" "payment_provider_mode" NOT NULL DEFAULT 'TEST',
    "testKeyId" VARCHAR(255),
    "liveKeyId" VARCHAR(255),
    "testKeySecretEnc" TEXT,
    "testWebhookSecretEnc" TEXT,
    "liveKeySecretEnc" TEXT,
    "liveWebhookSecretEnc" TEXT,
    "currency" VARCHAR(3) NOT NULL DEFAULT 'INR',
    "minAmount" DECIMAL(15,2) NOT NULL DEFAULT 100,
    "maxAmount" DECIMAL(15,2) NOT NULL DEFAULT 200000,
    "quickAmounts" JSONB,
    "paymentLinkExpiryHours" INTEGER NOT NULL DEFAULT 24,
    "lastTestedAt" TIMESTAMPTZ,
    "lastTestStatus" VARCHAR(20),
    "lastTestMessage" TEXT,
    "metadata" JSONB,
    "createdBy" UUID,
    "updatedBy" UUID,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "payment_provider_configs_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "payment_orders" (
    "id" UUID NOT NULL,
    "kind" "payment_order_kind" NOT NULL,
    "provider" VARCHAR(50) NOT NULL,
    "mode" "payment_provider_mode" NOT NULL,
    "isTest" BOOLEAN NOT NULL DEFAULT false,
    "walletUserId" VARCHAR(255) NOT NULL,
    "clientCode" VARCHAR(50) NOT NULL DEFAULT 'DEFAULT',
    "subjectUserId" UUID,
    "payerName" VARCHAR(255),
    "payerEmail" VARCHAR(255),
    "payerPhone" VARCHAR(20),
    "amount" DECIMAL(15,2) NOT NULL,
    "amountPaise" INTEGER NOT NULL,
    "currency" VARCHAR(3) NOT NULL DEFAULT 'INR',
    "status" "payment_order_status" NOT NULL DEFAULT 'CREATED',
    "providerOrderId" VARCHAR(255),
    "providerLinkId" VARCHAR(255),
    "providerPaymentId" VARCHAR(255),
    "shortUrl" TEXT,
    "expiresAt" TIMESTAMPTZ,
    "externalReferenceId" VARCHAR(255),
    "externalTransactionId" VARCHAR(255),
    "creditedAt" TIMESTAMPTZ,
    "reconcileAttempts" INTEGER NOT NULL DEFAULT 0,
    "lastReconcileAt" TIMESTAMPTZ,
    "nextRetryAt" TIMESTAMPTZ,
    "reconcileError" TEXT,
    "needsManualAction" BOOLEAN NOT NULL DEFAULT false,
    "refundedAmount" DECIMAL(15,2) NOT NULL DEFAULT 0,
    "notes" TEXT,
    "gatewayData" JSONB,
    "createdBy" UUID,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "payment_orders_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "payment_webhook_events" (
    "id" UUID NOT NULL,
    "provider" VARCHAR(50) NOT NULL,
    "providerEventId" VARCHAR(255) NOT NULL,
    "eventType" VARCHAR(100) NOT NULL,
    "paymentOrderId" UUID,
    "signatureValid" BOOLEAN NOT NULL DEFAULT false,
    "processed" BOOLEAN NOT NULL DEFAULT false,
    "processingError" TEXT,
    "payload" JSONB NOT NULL,
    "headers" JSONB,
    "receivedAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "processedAt" TIMESTAMPTZ,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "payment_webhook_events_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "manual_topup_requests" (
    "id" UUID NOT NULL,
    "walletUserId" VARCHAR(255) NOT NULL,
    "clientCode" VARCHAR(50) NOT NULL DEFAULT 'DEFAULT',
    "subjectUserId" UUID,
    "amount" DECIMAL(15,2) NOT NULL,
    "currency" VARCHAR(3) NOT NULL DEFAULT 'INR',
    "reason" TEXT NOT NULL,
    "externalReference" VARCHAR(255) NOT NULL,
    "status" "manual_topup_status" NOT NULL DEFAULT 'PENDING_APPROVAL',
    "thresholdAtRequest" DECIMAL(15,2) NOT NULL,
    "capAtRequest" DECIMAL(15,2) NOT NULL,
    "requestedBy" UUID NOT NULL,
    "requestedAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "reviewedBy" UUID,
    "reviewedAt" TIMESTAMPTZ,
    "reviewRemarks" TEXT,
    "externalReferenceId" VARCHAR(255),
    "externalTransactionId" VARCHAR(255),
    "creditedAt" TIMESTAMPTZ,
    "creditError" TEXT,
    "ipAddress" VARCHAR(45),
    "userAgent" TEXT,
    "metadata" JSONB,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "manual_topup_requests_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "wallet_topup_policies" (
    "id" UUID NOT NULL,
    "clientId" UUID,
    "manualMaxPerTransaction" DECIMAL(15,2) NOT NULL DEFAULT 100000,
    "manualApprovalThreshold" DECIMAL(15,2) NOT NULL DEFAULT 25000,
    "manualMaxPerDayPerUser" DECIMAL(15,2),
    "requireReason" BOOLEAN NOT NULL DEFAULT true,
    "requireReference" BOOLEAN NOT NULL DEFAULT true,
    "updatedBy" UUID,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "wallet_topup_policies_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "payment_provider_configs_isEnabled_idx" ON "payment_provider_configs"("isEnabled");

-- CreateIndex
CREATE UNIQUE INDEX "payment_provider_configs_provider_clientId_key" ON "payment_provider_configs"("provider", "clientId");

-- CreateIndex
CREATE INDEX "payment_orders_walletUserId_clientCode_idx" ON "payment_orders"("walletUserId", "clientCode");

-- CreateIndex
CREATE INDEX "payment_orders_subjectUserId_idx" ON "payment_orders"("subjectUserId");

-- CreateIndex
CREATE INDEX "payment_orders_status_idx" ON "payment_orders"("status");

-- CreateIndex
CREATE INDEX "payment_orders_status_nextRetryAt_idx" ON "payment_orders"("status", "nextRetryAt");

-- CreateIndex
CREATE INDEX "payment_orders_providerOrderId_idx" ON "payment_orders"("providerOrderId");

-- CreateIndex
CREATE INDEX "payment_orders_providerLinkId_idx" ON "payment_orders"("providerLinkId");

-- CreateIndex
CREATE INDEX "payment_orders_kind_createdAt_idx" ON "payment_orders"("kind", "createdAt");

-- CreateIndex
CREATE INDEX "payment_orders_createdBy_idx" ON "payment_orders"("createdBy");

-- CreateIndex
CREATE UNIQUE INDEX "payment_orders_provider_providerPaymentId_key" ON "payment_orders"("provider", "providerPaymentId");

-- CreateIndex
CREATE INDEX "payment_webhook_events_paymentOrderId_idx" ON "payment_webhook_events"("paymentOrderId");

-- CreateIndex
CREATE INDEX "payment_webhook_events_eventType_idx" ON "payment_webhook_events"("eventType");

-- CreateIndex
CREATE INDEX "payment_webhook_events_processed_idx" ON "payment_webhook_events"("processed");

-- CreateIndex
CREATE INDEX "payment_webhook_events_receivedAt_idx" ON "payment_webhook_events"("receivedAt");

-- CreateIndex
CREATE UNIQUE INDEX "payment_webhook_events_provider_providerEventId_key" ON "payment_webhook_events"("provider", "providerEventId");

-- CreateIndex
CREATE INDEX "manual_topup_requests_status_requestedAt_idx" ON "manual_topup_requests"("status", "requestedAt");

-- CreateIndex
CREATE INDEX "manual_topup_requests_walletUserId_clientCode_idx" ON "manual_topup_requests"("walletUserId", "clientCode");

-- CreateIndex
CREATE INDEX "manual_topup_requests_requestedBy_idx" ON "manual_topup_requests"("requestedBy");

-- CreateIndex
CREATE INDEX "manual_topup_requests_reviewedBy_idx" ON "manual_topup_requests"("reviewedBy");

-- CreateIndex
CREATE UNIQUE INDEX "manual_topup_requests_externalReferenceId_key" ON "manual_topup_requests"("externalReferenceId");

-- CreateIndex
CREATE INDEX "wallet_topup_policies_clientId_idx" ON "wallet_topup_policies"("clientId");

-- AddForeignKey
ALTER TABLE "payment_webhook_events" ADD CONSTRAINT "payment_webhook_events_paymentOrderId_fkey" FOREIGN KEY ("paymentOrderId") REFERENCES "payment_orders"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- ============================================================
-- Partial unique indexes (hand-written)
-- Prisma's schema language cannot express WHERE-clause (partial) unique
-- indexes as of prisma 5.x, so these are raw migration DDL. This does not
-- violate the "Prisma ORM only" rule, which governs application query code
-- in controllers/services, not migration files.
-- Precedent: shipment-service migration
-- 20260822120000_add_one_tax_invoice_per_shipment_index
-- ============================================================

-- Only ONE platform-level (clientId IS NULL) config row per provider.
-- The plain @@unique([provider, clientId]) above cannot enforce this because
-- Postgres treats NULLs as distinct.
CREATE UNIQUE INDEX "payment_provider_configs_provider_platform_uniq"
ON "payment_provider_configs" ("provider")
WHERE "clientId" IS NULL;

-- Never two orders claiming the same provider payment id. Scoped to
-- NOT NULL so the many rows still awaiting a payment id do not collide.
CREATE UNIQUE INDEX "payment_orders_provider_payment_uniq"
ON "payment_orders" ("provider", "providerPaymentId")
WHERE "providerPaymentId" IS NOT NULL;

-- Exactly one platform-level top-up policy row.
CREATE UNIQUE INDEX "wallet_topup_policies_platform_uniq"
ON "wallet_topup_policies" (("clientId" IS NULL))
WHERE "clientId" IS NULL;
